name: Production
'on':
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: yarn
      - run: yarn lint

  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: yarn
      - run: yarn tailwind

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USER}}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            brucewyne/thefractionalcto:build-${{ github.run_number }}
            brucewyne/thefractionalcto:latest

  deploy:
    name: Deploy Image to GCP Cloud Run
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{secrets.GCP_SERVICE_KEY_JSON}}

      - name: Update Image
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'thefractionalcto'
          image: 'brucewyne/thefractionalcto:build-${{ github.run_number }}'
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT}}

  cdn:
    name: Cloudflare Cache Purge
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Purge Cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

